"""Creacion tabla gastos

Revision ID: 2cf44c43df27
Revises: 
Create Date: 2025-07-08 21:34:07.823603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cf44c43df27'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gastos', schema=None) as batch_op:
        batch_op.alter_column('descripcion',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               nullable=False)
        batch_op.drop_column('categoria')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gastos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.alter_column('descripcion',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###
